# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2274b44ffaaa8db17db78b256b94686ea84b8a75f9d502d1bf08c45fe880e04aa2462155e675774a57769a53384531410c8866f61b5d7c7177022eb859789411

test:
  secret_key_base: 346df0d92a37befe4db2282fdd2972c403c93d65f4bf7bd34ee4075405d92639b51b7fee5991e25ef49e30c37df5ea2ea1274e9f42bf8f64180a9d5cd4e90cab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
